Feature openapi add interface
MoeGolibrary/moegoapis pull request #3
Opened 2024-04-30 07:33 UTC by KaihongZhang

- 定义agreemment、agreemmentrecord模型
- 新增agreement的get list接口
- 新增unsigned_agreement_record接口

2024-04-30 08:13 UTC, haozhixu3 requested changes

2024-04-30 08:13 UTC, haozhixu3 commented on moego/business/agreement/v1/agreement.proto
> +  // apply for services type, see the enum definition in ServiceType
这个service type是api definitions 的定义，外部用户看不见

2024-04-30 08:13 UTC, haozhixu3 commented on moego/business/agreement/v1/agreement_service.proto
> +    option (google.api.http) = {get: "/v1/agreements/sign_url/{id}"};
/v1/agreements/{id}/sign_url 这样应该合理一点

2024-04-30 08:19 UTC, haozhixu3 requested changes

2024-04-30 08:19 UTC, haozhixu3 commented on moego/business/agreement/v1/agreement_service.proto
> +message UnsignedAgreementRequest {
这个命名像是要去 unsign 一个agreement，GetAgreementSignURL 好点

2024-04-30 08:19 UTC, haozhixu3 commented on moego/business/agreement/v1/agreement_service.proto
> +  string send_url = 2;
sign_url

2024-04-30 08:32 UTC, KaihongZhang commented on moego/business/agreement/v1/agreement_service.proto
> +    option (google.api.http) = {get: "/v1/agreements/sign_url/{id}"};
嗯嗯好

2024-04-30 08:33 UTC, KaihongZhang commented on moego/business/agreement/v1/agreement.proto
> +  // apply for services type, see the enum definition in ServiceType
那就是不用return吗？

2024-04-30 08:33 UTC, KaihongZhang commented on moego/business/agreement/v1/agreement_service.proto
> +  string send_url = 2;
嗯嗯好

2024-04-30 08:37 UTC, AltaMills commented on moego/business/agreement/v1/agreement.proto
> +    STATUS_NORMAL = 1;
enum 除了 0 值都不要带前缀

2024-04-30 08:37 UTC, AltaMills commented on moego/business/agreement/v1/agreement.proto
> +  int32 service_types = 6;
这里要么直接提供 enum 类型，要么就不给这个参数了

2024-04-30 08:37 UTC, AltaMills commented on moego/business/agreement/v1/agreement.proto
> +  string agreement_title = 7;
不要带 message 命名相同的前缀，不然字段的使用就会从 agreement.title 变成 agreement.agreement_title

2024-04-30 08:37 UTC, AltaMills commented on moego/business/agreement/v1/agreement.proto
> +  int64 create_time = 14;
timestamp 统一用 google.protobuf.Timestamp

2024-04-30 08:37 UTC, AltaMills commented on moego/business/agreement/v1/agreement_service.proto
> +    option (google.api.http) = {get: "/v1/agreements/sign_url/{id}"};
同意，另外这个方法应该叫 GetAgreementSignLink，有些 agreement 是可以被反复签的，这里用 unsigned 不够准确

2024-04-30 08:58 UTC, haozhixu3 commented on moego/business/agreement/v1/agreement_service.proto
> +    option (google.api.http) = {get: "/v1/agreements/sign_url/{id}"};
如果下面叫GetAgreementSignLink，path这里和后面返回的字段也统一叫link吧，不叫url

2024-04-30 10:00 UTC, haozhixu3 commented on moego/business/agreement/v1/agreement.proto
> +  // apply for services type, see the enum definition in ServiceType
我的意思是你注释see the enum definition in ServiceType，用户也看不见呀🐶

2024-04-30 10:34 UTC, KaihongZhang commented on moego/business/agreement/v1/agreement.proto
> +    STATUS_NORMAL = 1;
不带前缀的话有些变量会冲突诶

2024-05-06 01:27 UTC, KaihongZhang commented on moego/business/agreement/v1/agreement.proto
> +  // apply for services type, see the enum definition in ServiceType
那我先把不必要的字段删除，后续如果需要再加上来

2024-05-06 02:04 UTC, haozhixu3 approved these changes

2024-05-06 02:08 UTC, AltaMills approved these changes

2024-05-06 02:10 UTC, merged